
services:
  postgres:
    image: postgres:15
    container_name: fixit-postgres
    environment:
      POSTGRES_DB: fixit
      POSTGRES_USER: fixit
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fixit -d fixit"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: