// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fixit/engine/ent/post"
	"fixit/engine/ent/predicate"
	"fixit/engine/ent/user"
	"fixit/engine/ent/vote"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
)

// VoteUpdate is the builder for updating Vote entities.
type VoteUpdate struct {
	config
	hooks    []Hook
	mutation *VoteMutation
}

// Where appends a list predicates to the VoteUpdate builder.
func (vu *VoteUpdate) Where(ps ...predicate.Vote) *VoteUpdate {
	vu.mutation.Where(ps...)
	return vu
}

// SetKind sets the "kind" field.
func (vu *VoteUpdate) SetKind(s string) *VoteUpdate {
	vu.mutation.SetKind(s)
	return vu
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (vu *VoteUpdate) SetNillableKind(s *string) *VoteUpdate {
	if s != nil {
		vu.SetKind(*s)
	}
	return vu
}

// SetValue sets the "value" field.
func (vu *VoteUpdate) SetValue(i int) *VoteUpdate {
	vu.mutation.ResetValue()
	vu.mutation.SetValue(i)
	return vu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (vu *VoteUpdate) SetNillableValue(i *int) *VoteUpdate {
	if i != nil {
		vu.SetValue(*i)
	}
	return vu
}

// AddValue adds i to the "value" field.
func (vu *VoteUpdate) AddValue(i int) *VoteUpdate {
	vu.mutation.AddValue(i)
	return vu
}

// SetUpdatedAt sets the "updated_at" field.
func (vu *VoteUpdate) SetUpdatedAt(t time.Time) *VoteUpdate {
	vu.mutation.SetUpdatedAt(t)
	return vu
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (vu *VoteUpdate) SetPostID(id uuid.UUID) *VoteUpdate {
	vu.mutation.SetPostID(id)
	return vu
}

// SetPost sets the "post" edge to the Post entity.
func (vu *VoteUpdate) SetPost(p *Post) *VoteUpdate {
	return vu.SetPostID(p.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (vu *VoteUpdate) SetUserID(id uuid.UUID) *VoteUpdate {
	vu.mutation.SetUserID(id)
	return vu
}

// SetUser sets the "user" edge to the User entity.
func (vu *VoteUpdate) SetUser(u *User) *VoteUpdate {
	return vu.SetUserID(u.ID)
}

// Mutation returns the VoteMutation object of the builder.
func (vu *VoteUpdate) Mutation() *VoteMutation {
	return vu.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (vu *VoteUpdate) ClearPost() *VoteUpdate {
	vu.mutation.ClearPost()
	return vu
}

// ClearUser clears the "user" edge to the User entity.
func (vu *VoteUpdate) ClearUser() *VoteUpdate {
	vu.mutation.ClearUser()
	return vu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vu *VoteUpdate) Save(ctx context.Context) (int, error) {
	vu.defaults()
	return withHooks(ctx, vu.sqlSave, vu.mutation, vu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vu *VoteUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *VoteUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *VoteUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vu *VoteUpdate) defaults() {
	if _, ok := vu.mutation.UpdatedAt(); !ok {
		v := vote.UpdateDefaultUpdatedAt()
		vu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vu *VoteUpdate) check() error {
	if vu.mutation.PostCleared() && len(vu.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.post"`)
	}
	if vu.mutation.UserCleared() && len(vu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.user"`)
	}
	return nil
}

func (vu *VoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := vu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(vote.Table, vote.Columns, sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID))
	if ps := vu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vu.mutation.Kind(); ok {
		_spec.SetField(vote.FieldKind, field.TypeString, value)
	}
	if value, ok := vu.mutation.Value(); ok {
		_spec.SetField(vote.FieldValue, field.TypeInt, value)
	}
	if value, ok := vu.mutation.AddedValue(); ok {
		_spec.AddField(vote.FieldValue, field.TypeInt, value)
	}
	if value, ok := vu.mutation.UpdatedAt(); ok {
		_spec.SetField(vote.FieldUpdatedAt, field.TypeTime, value)
	}
	if vu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vote.PostTable,
			Columns: []string{vote.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vote.PostTable,
			Columns: []string{vote.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vote.UserTable,
			Columns: []string{vote.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vote.UserTable,
			Columns: []string{vote.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vu.mutation.done = true
	return n, nil
}

// VoteUpdateOne is the builder for updating a single Vote entity.
type VoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VoteMutation
}

// SetKind sets the "kind" field.
func (vuo *VoteUpdateOne) SetKind(s string) *VoteUpdateOne {
	vuo.mutation.SetKind(s)
	return vuo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (vuo *VoteUpdateOne) SetNillableKind(s *string) *VoteUpdateOne {
	if s != nil {
		vuo.SetKind(*s)
	}
	return vuo
}

// SetValue sets the "value" field.
func (vuo *VoteUpdateOne) SetValue(i int) *VoteUpdateOne {
	vuo.mutation.ResetValue()
	vuo.mutation.SetValue(i)
	return vuo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (vuo *VoteUpdateOne) SetNillableValue(i *int) *VoteUpdateOne {
	if i != nil {
		vuo.SetValue(*i)
	}
	return vuo
}

// AddValue adds i to the "value" field.
func (vuo *VoteUpdateOne) AddValue(i int) *VoteUpdateOne {
	vuo.mutation.AddValue(i)
	return vuo
}

// SetUpdatedAt sets the "updated_at" field.
func (vuo *VoteUpdateOne) SetUpdatedAt(t time.Time) *VoteUpdateOne {
	vuo.mutation.SetUpdatedAt(t)
	return vuo
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (vuo *VoteUpdateOne) SetPostID(id uuid.UUID) *VoteUpdateOne {
	vuo.mutation.SetPostID(id)
	return vuo
}

// SetPost sets the "post" edge to the Post entity.
func (vuo *VoteUpdateOne) SetPost(p *Post) *VoteUpdateOne {
	return vuo.SetPostID(p.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (vuo *VoteUpdateOne) SetUserID(id uuid.UUID) *VoteUpdateOne {
	vuo.mutation.SetUserID(id)
	return vuo
}

// SetUser sets the "user" edge to the User entity.
func (vuo *VoteUpdateOne) SetUser(u *User) *VoteUpdateOne {
	return vuo.SetUserID(u.ID)
}

// Mutation returns the VoteMutation object of the builder.
func (vuo *VoteUpdateOne) Mutation() *VoteMutation {
	return vuo.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (vuo *VoteUpdateOne) ClearPost() *VoteUpdateOne {
	vuo.mutation.ClearPost()
	return vuo
}

// ClearUser clears the "user" edge to the User entity.
func (vuo *VoteUpdateOne) ClearUser() *VoteUpdateOne {
	vuo.mutation.ClearUser()
	return vuo
}

// Where appends a list predicates to the VoteUpdate builder.
func (vuo *VoteUpdateOne) Where(ps ...predicate.Vote) *VoteUpdateOne {
	vuo.mutation.Where(ps...)
	return vuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vuo *VoteUpdateOne) Select(field string, fields ...string) *VoteUpdateOne {
	vuo.fields = append([]string{field}, fields...)
	return vuo
}

// Save executes the query and returns the updated Vote entity.
func (vuo *VoteUpdateOne) Save(ctx context.Context) (*Vote, error) {
	vuo.defaults()
	return withHooks(ctx, vuo.sqlSave, vuo.mutation, vuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *VoteUpdateOne) SaveX(ctx context.Context) *Vote {
	node, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vuo *VoteUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *VoteUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vuo *VoteUpdateOne) defaults() {
	if _, ok := vuo.mutation.UpdatedAt(); !ok {
		v := vote.UpdateDefaultUpdatedAt()
		vuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vuo *VoteUpdateOne) check() error {
	if vuo.mutation.PostCleared() && len(vuo.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.post"`)
	}
	if vuo.mutation.UserCleared() && len(vuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vote.user"`)
	}
	return nil
}

func (vuo *VoteUpdateOne) sqlSave(ctx context.Context) (_node *Vote, err error) {
	if err := vuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vote.Table, vote.Columns, sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID))
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Vote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vote.FieldID)
		for _, f := range fields {
			if !vote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vuo.mutation.Kind(); ok {
		_spec.SetField(vote.FieldKind, field.TypeString, value)
	}
	if value, ok := vuo.mutation.Value(); ok {
		_spec.SetField(vote.FieldValue, field.TypeInt, value)
	}
	if value, ok := vuo.mutation.AddedValue(); ok {
		_spec.AddField(vote.FieldValue, field.TypeInt, value)
	}
	if value, ok := vuo.mutation.UpdatedAt(); ok {
		_spec.SetField(vote.FieldUpdatedAt, field.TypeTime, value)
	}
	if vuo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vote.PostTable,
			Columns: []string{vote.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vote.PostTable,
			Columns: []string{vote.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vote.UserTable,
			Columns: []string{vote.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vote.UserTable,
			Columns: []string{vote.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Vote{config: vuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vuo.mutation.done = true
	return _node, nil
}
